version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dealer-postgres
    environment:
      POSTGRES_DB: dealer_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - dealer-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dealer-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dealer_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - dealer-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  dealer-network:
    driver: bridge
